export const strings = {
  EN: {
    appTitle: 'JIBON TAILORS',
    tagline: 'Professional Tailoring Management System',
    dashboard: 'Dashboard',
    newOrder: 'New Order',
    orders: 'Orders',
    catalog: 'Catalog',
    dailyAccounts: 'Daily Accounts',
    karigar: 'Karigar Ledger',
    tailorRecords: 'Karigar Ledger',
    back: 'Back',
    changeStatus: 'Change Status:',
    orderDateLabel: 'Order Date',
    deliveryDateLabel: 'Delivery',
    sendInvoicePngWhatsApp: 'Send Invoice (PNG) to WhatsApp',
    sendReadyWhatsAppBtn: 'Send Dress Ready WhatsApp Alert',
    readyPromptTitle: 'Dress tailored & ready for pickup! 👗✨',
    readyPromptSub: 'Send WhatsApp pickup notification to customer',
    photosAttached: 'Photos',
    noPhoto: 'No Photo',
    viewLarge: 'View Large',
    removePhoto: 'Remove',
    paymentHistory: 'Payment & Deposit Receipts History',
    navDashboard: 'Dashboard',
    navNewOrder: '+Order',
    navCatalog: 'Catalog',
    navKarigar: 'Karigar',
    navExpenses: 'Expense & Deposit',
    navSettings: 'Settings',
    appSubTitle: 'Tailoring & Invoice Management System',
    measurements: 'Measurements',
    aiBusinessManager: 'AI Business Manager',
    customers: 'Customers',
    expenses: 'Expenses & Cash Deposit',
    reports: 'Reports & Analytics',
    settings: 'Settings',
    // Dashboard Cards
    totalInvoices: 'Total Invoices',
    totalPieces: 'Total Pieces',
    totalSales: 'Total Sales',
    totalAdvance: 'Total Advance Received',
    remainingDue: 'Total Remaining Due',
    recentOrders: 'Recent Orders',
    downloadBackup: 'Download Backup',
    restoreData: 'Restore Data',
    visualGuide: 'Measurement Guide',
    orderSummary: 'Order Summary',
    noOrdersFound: 'No orders found matching your search.',
    filterAll: 'All Orders',
    filterPending: 'Pending',
    filterInProgress: 'In Progress',
    filterReady: 'Ready',
    filterDelivered: 'Delivered',
    
    // Order / Invoice Form
    customerInfo: '1. Customer Information',
    customerName: 'Customer Name *',
    mobileNumber: 'Mobile Number *',
    addressLocation: 'Address / Location',
    orderDate: 'Order Date *',
    deliveryDate: 'Delivery Date *',
    dressType: 'Dress Type',
    orderStatus: 'Order Status',
    invoiceId: 'Invoice ID',
    // Statuses
    statusPending: 'Pending',
    statusInProgress: 'In Progress (Cutting/Sewing)',
    statusReady: 'Ready for Pickup',
    statusDelivered: 'Delivered',
    statusCancelled: 'Cancelled',
    // Items & Billing
    orderItems: '2. Order Items & Billing',
    addItem: '+ Add New Item',
    selectFromCatalog: 'Select from Catalog',
    description: 'Work Description',
    quantity: 'Quantity (Pcs)',
    unitPrice: 'Unit Price',
    totalPrice: 'Total Price',
    subtotal: 'Subtotal',
    discount: 'Discount',
    netTotal: 'Net Total Amount',
    advanceDeposit: 'Advance Deposit Received',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    bank: 'Bank Transfer / bKash',
    bankReference: 'Bank Ref / Trx ID',
    // Measurements
    measurementsBook: '4. Measurement Book (inches)',
    length: 'Length',
    bodyChest: 'Body / Chest',
    waist: 'Waist',
    hip: 'Hip',
    shoulder: 'Shoulder',
    sleeve: 'Sleeve',
    neck: 'Neck',
    flareBottom: 'Flare / Bottom',
    designNotes: 'Design Notes',
    specialInstructions: 'Special Stitching Instructions',
    aiEstimate: 'AI Measurement Estimate',
    // Camera / Gallery
    attachPhotos: '3. Cloth Sample & Design Photos',
    camera: 'CAMERA',
    gallery: 'GALLERY',
    clothPhoto: '1. Cloth Fabric Photo',
    dressDesignPhoto: '2. Dress Design / Model Photo',
    customerDesignPhoto: '3. Customer Reference Sketch',
    extraPhoto: '4. Additional Sample Photo',
    takePhoto: 'Take Live Photo',
    chooseFromGallery: 'Choose from Files',
    deletePhoto: 'Delete Photo',
    // Actions
    save: 'Save',
    saveInvoice: 'Save Invoice',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    printInvoice: 'Print Slip',
    saveToGallery: 'Save to Gallery (PNG)',
    shareInvoice: 'Share',
    sendWhatsApp: 'WhatsApp Message',
    sendWhatsAppPng: 'Send Invoice PNG via WhatsApp',
    sendReadyWhatsApp: 'Send Dress Ready Alert to WhatsApp',
    addPayment: '+ Add Due Payment',
    cancel: 'Cancel',
    search: 'Search (Name, Phone, Invoice #)...',
    close: 'Close',
    confirmDelete: 'Are you sure you want to permanently delete this record?',
    
    // Karigar / Tailor Ledger
    karigarLedgerTitle: 'Karigar (Tailor) Work & Wage Ledger',
    karigarSubTitle: 'Track tailor cutting, sewing pieces, piece rates, advances/payments, and calculate aggregate balance per karigar.',
    addWorkRecord: '+ Add Karigar Work / Advance',
    editWorkRecord: 'Edit Karigar Entry',
    tailorName: 'Karigar Name *',
    tailorPhone: 'Mobile Number',
    workType: 'Work Type',
    cutting: 'Cutting',
    sewing: 'Sewing',
    cuttingAndSewing: 'Cutting & Sewing',
    otherWork: 'Other Work',
    cuttingPieces: 'Cutting Pieces',
    sewingPieces: 'Sewing Pieces',
    totalPiecesCount: 'Total Pieces (Pcs)',
    ratePerPiece: 'Rate per Piece',
    totalWorkValue: 'Total Wage / Bill',
    paidAmount: 'Money Taken / Paid',
    balanceDue: 'Remaining Due to Karigar',
    allEntriesTab: 'Itemized Work Entries',
    groupedKarigarTab: 'Karigar Summary (Grouped by Name & Phone)',
    totalKarigars: 'Total Karigars',
    totalCuttingPcs: 'Total Cutting Pieces',
    totalSewingPcs: 'Total Sewing Pieces',
    totalKarigarWage: 'Total Wage Earned',
    totalKarigarPaid: 'Total Paid / Advance',
    totalKarigarDue: 'Total Balance Due',
    karigarStatement: 'Karigar Account Statement',
    noKarigarFound: 'No karigar records found.',
    printStatement: 'Print Karigar Statement',
    
    // Expenses & Deposits
    expenseDepositTitle: 'Expenses & Cash Deposit Register',
    expenseDepositSubTitle: 'Keep record of daily shop expenses and cash deposits in the cash register.',
    addExpenseDeposit: '+ Add Expense / Cash Deposit',
    editExpenseDeposit: 'Edit Transaction',
    entryType: 'Transaction Type',
    expenseType: '💸 Shop Expense',
    depositType: '💰 Cash Deposit',
    cashDeposit: 'Cash Deposit',
    shopExpense: 'Shop Expense',
    totalDeposits: 'Total Cash Deposits',
    totalExpenses: 'Total Shop Expenses',
    netCashBalance: 'Net Cash in Register (In Hand)',
    allTransactions: 'All Records',
    onlyDeposits: 'Cash Deposits Only',
    onlyExpenses: 'Expenses Only',
    category: 'Category',
    amount: 'Amount',
    date: 'Date',
    paymentMethodLabel: 'Payment Method / Account',
    noTransactionsFound: 'No expense or deposit records found.',
    
    // Catalog
    catalogTitle: 'Dress & Design Catalog',
    dressName: 'Dress Name',
    catalogCode: 'Catalog Code',
    modelSize: 'Model Size',
    addOrderFromCatalog: 'ADD ORDER',
    shareCatalogCard: 'SHARE',
    sendCatalogWhatsAppPng: 'Send via WhatsApp (with Photo)',
    addCatalogItem: '+ Add Catalog Design',
    noCatalogFound: 'No catalog designs found.',
    
    // Reports
    fromDate: 'From Date',
    toDate: 'To Date',
    applyFilter: 'Apply Filter',
    avgOrderValue: 'Average Order Value',
    cashPayments: 'Cash Payments',
    bankPayments: 'Bank Payments',
    // Settings
    shopSettings: 'Shop Profile & Settings',
    shopName: 'Shop Name',
    shopAddress: 'Shop Address',
    crNumber: 'CR Number / Trade License',
    currency: 'Currency Code (OMR, BDT, etc.)',
    multiShop: 'Multiple Shop Profiles',
    language: 'Language (English / বাংলা)',
  },
  BN: {
    appTitle: 'জীবন টেইলার্স',
    tagline: 'প্রফেশনাল টেইলারিং ও ইনভয়েস ম্যানেজমেন্ট',
    dashboard: 'ড্যাশবোর্ড',
    newOrder: 'নতুন অর্ডার',
    orders: 'অর্ডার সমূহ',
    catalog: 'ক্যাটালগ',
    dailyAccounts: 'দৈনিক হিসাব',
    karigar: 'কারিগর খাতা',
    tailorRecords: 'কারিগর খাতা',
    back: 'পেছনে যান',
    changeStatus: 'স্ট্যাটাস পরিবর্তন:',
    orderDateLabel: 'অর্ডারের তারিখ',
    deliveryDateLabel: 'ডেলিভারি',
    sendInvoicePngWhatsApp: 'WhatsApp এ ইনভয়েস (PNG) পাঠান',
    sendReadyWhatsAppBtn: 'কাপড় রেডি WhatsApp মেসেজ পাঠান',
    readyPromptTitle: 'পোশাক সেলাই সম্পন্ন ও সম্পূর্ণ রেডি! 👗✨',
    readyPromptSub: 'কাস্টমারকে WhatsApp-এ প্রস্তুত থাকার নোটিফিকেশন পাঠান',
    photosAttached: 'ছবি',
    noPhoto: 'ছবি নেই',
    viewLarge: 'বড় দেখুন',
    removePhoto: 'মুছুন',
    paymentHistory: 'পেমেন্ট ও জমা রশিদের ইতিহাস',
    navDashboard: 'ড্যাশবোর্ড',
    navNewOrder: '+অর্ডার',
    navCatalog: 'ক্যাটালগ',
    navKarigar: 'কারিগর',
    navExpenses: 'খরচ ও জমা',
    navSettings: 'সেটিংস',
    appSubTitle: 'টেইলারিং ও ইনভয়েস ম্যানেজমেন্ট সিস্টেম',
    measurements: 'মাপের খাতা',
    aiBusinessManager: 'AI বিজনেস ম্যানেজার',
    customers: 'কাস্টমার তালিকা',
    expenses: 'দোকান খরচ ও ক্যাশ জমা',
    reports: 'রিপোর্ট ও বিশ্লেষণ',
    settings: 'সেটিংস',
    // Dashboard Cards
    totalInvoices: 'মোট ইনভয়েস',
    totalPieces: 'মোট পোশাক (পিস)',
    totalSales: 'মোট বিক্রি (বিক্রয়)',
    totalAdvance: 'অগ্রিম গ্রহণ (এডভান্স)',
    remainingDue: 'মোট বাকি (বকেয়া)',
    recentOrders: 'সাম্প্রতিক অর্ডারসমূহ',
    downloadBackup: 'ব্যাকআপ ডাউনলোড',
    restoreData: 'ডাটা রিস্টোর',
    visualGuide: 'মাপের নির্দেশিকা',
    orderSummary: 'অর্ডার সারসংক্ষেপ',
    noOrdersFound: 'কোনো অর্ডার পাওয়া যায়নি।',
    filterAll: 'সকল অর্ডার',
    filterPending: 'পেন্ডিং',
    filterInProgress: 'চলমান',
    filterReady: 'রেডি',
    filterDelivered: 'ডেলিভারি',
    
    // Order / Invoice Form
    customerInfo: '১. কাস্টমার তথ্য',
    customerName: 'কাস্টমারের নাম *',
    mobileNumber: 'মোবাইল নাম্বার *',
    addressLocation: 'ঠিকানা / লোকেশন',
    orderDate: 'অর্ডার তারিখ *',
    deliveryDate: 'ডেলিভারি তারিখ *',
    dressType: 'পোশাকের ধরন',
    orderStatus: 'অর্ডারের অবস্থা',
    invoiceId: 'ইনভয়েস নং',
    // Statuses
    statusPending: 'পেন্ডিং (অপেক্ষমান)',
    statusInProgress: 'কাজ চলছে (কাটিং/সেলাই)',
    statusReady: 'কাপড় রেডি (ডেলিভারির জন্য প্রস্তুত)',
    statusDelivered: 'ডেলিভারি সম্পন্ন',
    statusCancelled: 'বাতিল',
    // Items & Billing
    orderItems: '২. অর্ডার আইটেম ও বিলিং হিসাব',
    addItem: '+ নতুন আইটেম যোগ করুন',
    selectFromCatalog: 'ক্যাটালগ থেকে নির্বাচন',
    description: 'কাজের বিবরণ',
    quantity: 'পরিমাণ (পিস)',
    unitPrice: 'দর (একক মূল্য)',
    totalPrice: 'মোট টাকা',
    subtotal: 'সাবটোটাল',
    discount: 'ডিসকাউন্ট (ছাড়)',
    netTotal: 'মোট প্রদেয় বিল',
    advanceDeposit: 'অগ্রিম জমা (এডভান্স)',
    paymentMethod: 'পরিশোধের মাধ্যম',
    cash: 'নগদ (Cash)',
    bank: 'ব্যাংক ট্রান্সফার / বিকাশ',
    bankReference: 'ট্রানজেকশন আইডি / রেফারেন্স',
    // Measurements
    measurementsBook: '৪. পোশাকের মাপের খাতা (ইঞ্চি)',
    length: 'ঝুল / লম্বা (Length)',
    bodyChest: 'বডি / বুক (Chest)',
    waist: 'কোমর (Waist)',
    hip: 'হিপ (Hip)',
    shoulder: 'পুঁট / তীর (Shoulder)',
    sleeve: 'হাতা (Sleeve)',
    neck: 'গলা (Neck)',
    flareBottom: 'ঘের / মহুরী (Flare)',
    designNotes: 'ডিজাইন নোট',
    specialInstructions: 'বিশেষ সেলাই নির্দেশনা',
    aiEstimate: 'AI অটো মাপ নির্ধারণ',
    // Camera / Gallery
    attachPhotos: '৩. কাপড়ের স্যাম্পল ও ডিজাইনের ছবি',
    camera: 'ক্যামেরা (Camera)',
    gallery: 'গ্যালারি (Files)',
    clothPhoto: '১. কাপড়ের ফেব্রিক ছবি',
    dressDesignPhoto: '২. ড্রেস ডিজাইন / মডেল ছবি',
    customerDesignPhoto: '৩. কাস্টমার স্কেচ / রেফারেন্স',
    extraPhoto: '৪. অতিরিক্ত রেফারেন্স ছবি',
    takePhoto: 'সরাসরি ছবি তুলুন',
    chooseFromGallery: 'গ্যালারি থেকে নিন',
    deletePhoto: 'ছবি মুছুন',
    // Actions
    save: 'সংরক্ষণ',
    saveInvoice: 'ইনভয়েস সেভ করুন',
    edit: 'সম্পাদনা',
    delete: 'মুছুন',
    view: 'দেখুন',
    printInvoice: 'প্রিন্ট রশিদ',
    saveToGallery: 'ছবি হিসেবে ডাউনলোড (PNG)',
    shareInvoice: 'শেয়ার করুন',
    sendWhatsApp: 'হোয়াটসঅ্যাপ মেসেজ',
    sendWhatsAppPng: 'হোয়াটসঅ্যাপে ইনভয়েস PNG পাঠান',
    sendReadyWhatsApp: 'কাপড় রেডি হোয়াটসঅ্যাপ মেসেজ পাঠান',
    addPayment: '+ বকেয়া জমা নিন',
    cancel: 'বাতিল',
    search: 'খুঁজুন (নাম, ফোন, আইডি)...',
    close: 'বন্ধ করুন',
    confirmDelete: 'আপনি কি নিশ্চিতভাবে এই রেকর্ডটি মুছে ফেলতে চান?',
    
    // Karigar / Tailor Ledger
    karigarLedgerTitle: 'কারিগরদের কাজের খাতা ও মজুরি হিসাব',
    karigarSubTitle: 'কারিগরদের নাম, মোবাইল নাম্বার, কাটিং ও সেলাই পিস, পিস রেট, টাকা নেওয়া ও বাকি পাওনার সামগ্রিক হিসাব।',
    addWorkRecord: '+ কারিগর কাজ / টাকা প্রদান এন্ট্রি',
    editWorkRecord: 'কারিগর হিসাব সম্পাদনা',
    tailorName: 'কারিগরের নাম *',
    tailorPhone: 'মোবাইল নাম্বার',
    workType: 'কাজের ধরন',
    cutting: 'কাটিং',
    sewing: 'সেলাই',
    cuttingAndSewing: 'কাটিং ও সেলাই',
    otherWork: 'অন্যান্য কাজ',
    cuttingPieces: 'কাটিং পিস',
    sewingPieces: 'সেলাই পিস',
    totalPiecesCount: 'মোট পরিমাণ (পিস)',
    ratePerPiece: 'পিস প্রতি রেট',
    totalWorkValue: 'মোট কাজের মজুরি',
    paidAmount: 'টাকা নেওয়া / প্রদান',
    balanceDue: 'বাকি পাওনা (বকেয়া)',
    allEntriesTab: 'আইটেমওয়ারি কাজের রেকর্ড',
    groupedKarigarTab: 'কারিগর সারসংক্ষেপ (নাম ও ফোন অনুযায়ী মোট হিসাব)',
    totalKarigars: 'মোট কারিগর',
    totalCuttingPcs: 'মোট কাটিং পিস',
    totalSewingPcs: 'মোট সেলাই পিস',
    totalKarigarWage: 'মোট মজুরি',
    totalKarigarPaid: 'মোট টাকা পরিশোধ',
    totalKarigarDue: 'মোট বাকি পাওনা',
    karigarStatement: 'কারিগরের পূর্ণাঙ্গ হিসাব স্টেটমেন্ট',
    noKarigarFound: 'কোনো কারিগর রেকর্ড পাওয়া যায়নি।',
    printStatement: 'কারিগর স্টেটমেন্ট প্রিন্ট',
    
    // Expenses & Deposits
    expenseDepositTitle: 'দোকান খরচ ও ক্যাশ জমা খাতা',
    expenseDepositSubTitle: 'দোকানের প্রতিদিনের বিবিধ খরচ এবং ক্যাশ বাক্সে নগদ ক্যাশ জমার নির্ভুল হিসাব।',
    addExpenseDeposit: '+ খরচ / ক্যাশ জমা এন্ট্রি',
    editExpenseDeposit: 'লেনদেন সম্পাদনা',
    entryType: 'লেনদেনের ধরন',
    expenseType: '💸 দোকান খরচ (Expense)',
    depositType: '💰 ক্যাশ জমা (Cash Deposit)',
    cashDeposit: 'ক্যাশ জমা',
    shopExpense: 'দোকান খরচ',
    totalDeposits: 'মোট ক্যাশ জমা',
    totalExpenses: 'মোট খরচ',
    netCashBalance: 'ক্যাশ বাক্সে অবশিষ্ট নগদ (Net Cash)',
    allTransactions: 'সকল রেকর্ড',
    onlyDeposits: 'শুধু ক্যাশ জমা',
    onlyExpenses: 'শুধু খরচ',
    category: 'ক্যাটাগরি',
    amount: 'টাকার পরিমাণ',
    date: 'তারিখ',
    paymentMethodLabel: 'পদ্ধতি / একাউন্ট',
    noTransactionsFound: 'কোনো খরচ বা জমার রেকর্ড পাওয়া যায়নি।',
    
    // Catalog
    catalogTitle: 'পোশাক ও ডিজাইনের ক্যাটালগ',
    dressName: 'পোশাকের নাম',
    catalogCode: 'ক্যাটালগ কোড',
    modelSize: 'মডেল সাইজ',
    addOrderFromCatalog: 'অর্ডারে যোগ করুন',
    shareCatalogCard: 'শেয়ার করুন',
    sendCatalogWhatsAppPng: 'হোয়াটসঅ্যাপে ছবি সহ পাঠান',
    addCatalogItem: '+ নতুন ডিজাইন যোগ করুন',
    noCatalogFound: 'কোনো ক্যাটালগ ডিজাইন পাওয়া যায়নি।',
    
    // Reports
    fromDate: 'শুরুর তারিখ',
    toDate: 'শেষ তারিখ',
    applyFilter: 'ফিল্টার করুন',
    avgOrderValue: 'গড় অর্ডার মূল্য',
    cashPayments: 'নগদ আদায়',
    bankPayments: 'ব্যাংক আদায়',
    // Settings
    shopSettings: 'দোকানের বিবরণ সেটিংস',
    shopName: 'দোকানের নাম',
    shopAddress: 'দোকানের ঠিকানা',
    crNumber: 'সিআর / ট্রেড লাইসেন্স নং',
    currency: 'মুদ্রা কোড (OMR, BDT, etc.)',
    multiShop: 'একাধিক শাখা / ব্রাঞ্চ পরিচালনা',
    language: 'ভাষা নির্বাচন (বাংলা / English / हिन्दी / العربية)',
  },
  HI: {
    appTitle: 'जीवन टेलर्स',
    tagline: 'पेशेवर सिलाई और चालान प्रबंधन प्रणाली',
    dashboard: 'डैशबोर्ड',
    newOrder: 'नया ऑर्डर',
    orders: 'ऑर्डर सूची',
    catalog: 'कैटलॉग',
    dailyAccounts: 'दैनिक हिसाब',
    karigar: 'कारीगर खाता',
    tailorRecords: 'कारीगर खाता',
    back: 'वापस जाएं',
    changeStatus: 'स्थिति बदलें:',
    orderDateLabel: 'ऑर्डर की तारीख',
    deliveryDateLabel: 'डिलीवरी तारीख',
    sendInvoicePngWhatsApp: 'WhatsApp पर चालान (PNG) भेजें',
    sendReadyWhatsAppBtn: 'कपड़ा तैयार WhatsApp अलर्ट भेजें',
    readyPromptTitle: 'पोशाक सिलकर तैयार है! 👗✨',
    readyPromptSub: 'ग्राहक को WhatsApp पर पिकअप सूचना भेजें',
    photosAttached: 'तस्वीरें',
    noPhoto: 'कोई फोटो नहीं',
    viewLarge: 'बड़ा देखें',
    removePhoto: 'हटाएं',
    paymentHistory: 'भुगतान और जमा रसीद इतिहास',
    navDashboard: 'डैशबोर्ड',
    navNewOrder: '+ऑर्डर',
    navCatalog: 'कैटलॉग',
    navKarigar: 'कारीगर',
    navExpenses: 'खर्च और जमा',
    navSettings: 'सेटिंग्स',
    appSubTitle: 'सिलाई और चालान प्रबंधन प्रणाली',
    measurements: 'नाप की किताब',
    aiBusinessManager: 'AI बिजनेस मैनेजर',
    customers: 'ग्राहक सूची',
    expenses: 'दुकान खर्च और जमा',
    reports: 'रिपोर्ट और विश्लेषण',
    settings: 'सेटिंग्स',
    // Dashboard Cards
    totalInvoices: 'कुल चालान',
    totalPieces: 'कुल पीस (कपड़े)',
    totalSales: 'कुल बिक्री (सेल)',
    totalAdvance: 'कुल अग्रिम जमा (Advance)',
    remainingDue: 'कुल बकाया राशि (Due)',
    recentOrders: 'हाल के ऑर्डर',
    downloadBackup: 'बैकअप डाउनलोड',
    restoreData: 'डेटा रीस्टोर',
    visualGuide: 'नाप गाइड',
    orderSummary: 'ऑर्डर सारांश',
    noOrdersFound: 'कोई ऑर्डर नहीं मिला।',
    filterAll: 'सभी ऑर्डर',
    filterPending: 'लंबित (Pending)',
    filterInProgress: 'प्रगति पर (In Progress)',
    filterReady: 'तैयार (Ready)',
    filterDelivered: 'डिलीवर किया गया',
    
    // Order / Invoice Form
    customerInfo: '1. ग्राहक जानकारी',
    customerName: 'ग्राहक का नाम *',
    mobileNumber: 'मोबाइल नंबर *',
    addressLocation: 'पता / स्थान',
    orderDate: 'ऑर्डर की तारीख *',
    deliveryDate: 'डिलीवरी की तारीख *',
    dressType: 'पोशाक का प्रकार',
    orderStatus: 'ऑर्डर की स्थिति',
    invoiceId: 'चालान संख्या',
    // Statuses
    statusPending: 'लंबित (Pending)',
    statusInProgress: 'काम जारी है (कटिंग/सिलाई)',
    statusReady: 'कपड़ा तैयार (पिकअप के लिए)',
    statusDelivered: 'डिलीवरी संपन्न',
    statusCancelled: 'रद्द',
    // Items & Billing
    orderItems: '2. ऑर्डर आइटम और बिलिंग',
    addItem: '+ नया आइटम जोड़ें',
    selectFromCatalog: 'कैटलॉग से चुनें',
    description: 'काम का विवरण',
    quantity: 'मात्रा (पीस)',
    unitPrice: 'दर (इकाई मूल्य)',
    totalPrice: 'कुल मूल्य',
    subtotal: 'उप-योग (Subtotal)',
    discount: 'छूट (Discount)',
    netTotal: 'कुल देय राशि (Net Total)',
    advanceDeposit: 'अग्रिम जमा (Advance Deposit)',
    paymentMethod: 'भुगतान विधि',
    cash: 'नकद (Cash)',
    bank: 'बैंक ट्रांसफर / यूपीआई',
    bankReference: 'लेन-देन आईडी / संदर्भ',
    // Measurements
    measurementsBook: '4. नाप की किताब (इंच)',
    length: 'लंबाई / झूल (Length)',
    bodyChest: 'सीना / छाती (Chest)',
    waist: 'कमर (Waist)',
    hip: 'हिप (Hip)',
    shoulder: 'कंधा / तीरा (Shoulder)',
    sleeve: 'आस्तीन / बांह (Sleeve)',
    neck: 'गला (Neck)',
    flareBottom: 'घेरा / मोहरी (Flare)',
    designNotes: 'डिज़ाइन नोट्स',
    specialInstructions: 'विशेष सिलाई निर्देश',
    aiEstimate: 'AI ऑटो नाप अनुमान',
    // Camera / Gallery
    attachPhotos: '3. कपड़े का नमूना और डिज़ाइन फोटो',
    camera: 'कैमरा (Camera)',
    gallery: 'गैलरी (Files)',
    clothPhoto: '1. कपड़े का फैब्रिक फोटो',
    dressDesignPhoto: '2. ड्रेस डिज़ाइन / मॉडल फोटो',
    customerDesignPhoto: '3. ग्राहक संदर्भ स्केच',
    extraPhoto: '4. अतिरिक्त संदर्भ फोटो',
    takePhoto: 'लाइव फोटो लें',
    chooseFromGallery: 'गैलरी से चुनें',
    deletePhoto: 'फोटो हटाएं',
    // Actions
    save: 'सहेजें (Save)',
    saveInvoice: 'चालान सहेजें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    view: 'देखें',
    printInvoice: 'रसीद प्रिंट करें',
    saveToGallery: 'PNG छवि के रूप में सहेजें',
    shareInvoice: 'साझा करें (Share)',
    sendWhatsApp: 'WhatsApp संदेश',
    sendWhatsAppPng: 'WhatsApp पर चालान PNG भेजें',
    sendReadyWhatsApp: 'कपड़ा तैयार WhatsApp अलर्ट भेजें',
    addPayment: '+ बकाया भुगतान जोड़ें',
    cancel: 'रद्द करें',
    search: 'खोजें (नाम, फोन, चालान #)...',
    close: 'बंद करें',
    confirmDelete: 'क्या आप वाकई इस रिकॉर्ड को हमेशा के लिए हटाना चाहते हैं?',
    
    // Karigar / Tailor Ledger
    karigarLedgerTitle: 'कारीगर काम और मजदूरी खाता',
    karigarSubTitle: 'कारीगरों के नाम, मोबाइल नंबर, कटिंग और सिलाई पीस, पीस रेट, भुगतान और शेष बकाया का पूरा हिसाब।',
    addWorkRecord: '+ कारीगर काम / भुगतान प्रविष्टि',
    editWorkRecord: 'कारीगर प्रविष्टि संपादित करें',
    tailorName: 'कारीगर का नाम *',
    tailorPhone: 'मोबाइल नंबर',
    workType: 'काम का प्रकार',
    cutting: 'कटिंग',
    sewing: 'सिलाई',
    cuttingAndSewing: 'कटिंग और सिलाई',
    otherWork: 'अन्य काम',
    cuttingPieces: 'कटिंग पीस',
    sewingPieces: 'सिलाई पीस',
    totalPiecesCount: 'कुल मात्रा (पीस)',
    ratePerPiece: 'प्रति पीस दर',
    totalWorkValue: 'कुल काम की मजदूरी',
    paidAmount: 'लिया गया / भुगतान राशि',
    balanceDue: 'कारीगर का शेष बकाया',
    allEntriesTab: 'मदवार काम प्रविष्टियाँ',
    groupedKarigarTab: 'कारीगर सारांश (नाम और फोन अनुसार)',
    totalKarigars: 'कुल कारीगर',
    totalCuttingPcs: 'कुल कटिंग पीस',
    totalSewingPcs: 'कुल सिलाई पीस',
    totalKarigarWage: 'कुल अर्जित मजदूरी',
    totalKarigarPaid: 'कुल भुगतान / अग्रिम',
    totalKarigarDue: 'कुल शेष बकाया',
    karigarStatement: 'कारीगर खाता विवरण',
    noKarigarFound: 'कोई कारीगर रिकॉर्ड नहीं मिला।',
    printStatement: 'कारीगर विवरण प्रिंट करें',
    
    // Expenses & Deposits
    expenseDepositTitle: 'दुकान खर्च और नकद जमा रजिस्टर',
    expenseDepositSubTitle: 'दुकान के दैनिक खर्चों और गल्ले में नकद जमा का सटीक हिसाब रखें।',
    addExpenseDeposit: '+ खर्च / नकद जमा जोड़ें',
    editExpenseDeposit: 'लेन-देन संपादित करें',
    entryType: 'लेन-देन प्रकार',
    expenseType: '💸 दुकान खर्च (Expense)',
    depositType: '💰 नकद जमा (Cash Deposit)',
    cashDeposit: 'नकद जमा',
    shopExpense: 'दुकान खर्च',
    totalDeposits: 'कुल नकद जमा',
    totalExpenses: 'कुल दुकान खर्च',
    netCashBalance: 'गल्ले में शेष नकद (Net Cash in Hand)',
    allTransactions: 'सभी रिकॉर्ड',
    onlyDeposits: 'केवल नकद जमा',
    onlyExpenses: 'केवल खर्च',
    category: 'श्रेणी (Category)',
    amount: 'राशि',
    date: 'तारीख',
    paymentMethodLabel: 'भुगतान विधि / खाता',
    noTransactionsFound: 'कोई खर्च या जमा रिकॉर्ड नहीं मिला।',
    
    // Catalog
    catalogTitle: 'पोशाक और डिज़ाइन कैटलॉग',
    dressName: 'पोशाक का नाम',
    catalogCode: 'कैटलॉग कोड',
    modelSize: 'मॉडल साइज़',
    addOrderFromCatalog: 'ऑर्डर में जोड़ें',
    shareCatalogCard: 'साझा करें',
    sendCatalogWhatsAppPng: 'तस्वीर के साथ WhatsApp भेजें',
    addCatalogItem: '+ नया डिज़ाइन जोड़ें',
    noCatalogFound: 'कोई कैटलॉग डिज़ाइन नहीं मिला।',
    
    // Reports
    fromDate: 'प्रारंभ तिथि',
    toDate: 'अंतिम तिथि',
    applyFilter: 'फ़िल्टर लागू करें',
    avgOrderValue: 'औसत ऑर्डर मूल्य',
    cashPayments: 'नकद प्राप्तियाँ',
    bankPayments: 'बैंक प्राप्तियाँ',
    // Settings
    shopSettings: 'दुकान प्रोफ़ाइल और सेटिंग्स',
    shopName: 'दुकान का नाम',
    shopAddress: 'दुकान का पता',
    crNumber: 'सीआर / ट्रेड लाइसेंस नंबर',
    currency: 'मुद्रा कोड (OMR, BDT, INR आदि)',
    multiShop: 'एकाधिक शाखा प्रोफ़ाइल',
    language: 'भाषा चयन (বাংলা / English / हिन्दी / العربية)',
  },
  AR: {
    appTitle: 'خياط الحياة',
    tagline: 'نظام إدارة الخياطة والفواتير الاحترافي',
    dashboard: 'لوحة التحكم',
    newOrder: 'طلب جديد',
    orders: 'قائمة الطلبات',
    catalog: 'كتالوج التصاميم',
    dailyAccounts: 'الحسابات اليومية',
    karigar: 'دفتر الخياطين',
    tailorRecords: 'سجل الخياطين',
    back: 'رجوع',
    changeStatus: 'تغيير الحالة:',
    orderDateLabel: 'تاريخ الطلب',
    deliveryDateLabel: 'تاريخ التسليم',
    sendInvoicePngWhatsApp: 'إرسال الفاتورة عبر واتساب (PNG)',
    sendReadyWhatsAppBtn: 'إرسال تنبيه جاهزية الملابس عبر واتساب',
    readyPromptTitle: 'الملابس جاهزة للاستلام! 👗✨',
    readyPromptSub: 'إرسال إشعار استلام للعميل عبر واتساب',
    photosAttached: 'الصور المرفقة',
    noPhoto: 'لا توجد صورة',
    viewLarge: 'عرض بالحجم الكامل',
    removePhoto: 'حذف',
    paymentHistory: 'سجل المدفوعات والإيصالات',
    navDashboard: 'الرئيسية',
    navNewOrder: '+طلب',
    navCatalog: 'الكتالوج',
    navKarigar: 'الخياطين',
    navExpenses: 'المصروفات',
    navSettings: 'الإعدادات',
    appSubTitle: 'نظام إدارة الخياطة وتفصيل الملابس والفواتير',
    measurements: 'دفتر المقاسات',
    aiBusinessManager: 'مدير الأعمال الذكي (AI)',
    customers: 'سجل العملاء',
    expenses: 'المصروفات والإيداعات',
    reports: 'التقارير والإحصائيات',
    settings: 'الإعدادات',
    // Dashboard Cards
    totalInvoices: 'إجمالي الفواتير',
    totalPieces: 'إجمالي القطع',
    totalSales: 'إجمالي المبيعات',
    totalAdvance: 'إجمالي العربون المستلم',
    remainingDue: 'إجمالي المتبقي (الديون)',
    recentOrders: 'أحدث الطلبات',
    downloadBackup: 'تنزيل نسخة احتياطية',
    restoreData: 'استعادة البيانات',
    visualGuide: 'دليل أخذ المقاسات',
    orderSummary: 'ملخص الطلب',
    noOrdersFound: 'لم يتم العثور على طلبات مطابقة.',
    filterAll: 'جميع الطلبات',
    filterPending: 'قيد الانتظار',
    filterInProgress: 'قيد التفصيل / الخياطة',
    filterReady: 'جاهز للاستلام',
    filterDelivered: 'تم التسليم',
    
    // Order / Invoice Form
    customerInfo: '١. بيانات العميل',
    customerName: 'اسم العميل *',
    mobileNumber: 'رقم الهاتف / الجوال *',
    addressLocation: 'العنوان / الموقع',
    orderDate: 'تاريخ الطلب *',
    deliveryDate: 'تاريخ التسليم *',
    dressType: 'نوع الملابس / الفستان',
    orderStatus: 'حالة الطلب',
    invoiceId: 'رقم الفاتورة',
    // Statuses
    statusPending: 'قيد الانتظار (Pending)',
    statusInProgress: 'جاري العمل (قص / خياطة)',
    statusReady: 'الملابس جاهزة للاستلام',
    statusDelivered: 'تم التسليم للعميل',
    statusCancelled: 'ملغي',
    // Items & Billing
    orderItems: '٢. تفاصيل البنود والحساب',
    addItem: '+ إضافة بند جديد',
    selectFromCatalog: 'اختيار من الكتالوج',
    description: 'وصف العمل / التفصيل',
    quantity: 'الكمية (قطعة)',
    unitPrice: 'سعر الوحدة',
    totalPrice: 'الإجمالي',
    subtotal: 'المجموع الفرعي',
    discount: 'الخصم',
    netTotal: 'المبلغ الصافي المستحق',
    advanceDeposit: 'العربون المدفوع مقدماً',
    paymentMethod: 'طريقة الدفع',
    cash: 'نقداً (Cash)',
    bank: 'تحويل بنكي / إلكتروني',
    bankReference: 'رقم المعاملة / المرجع',
    // Measurements
    measurementsBook: '٤. دفتر المقاسات (بالبوصة)',
    length: 'الطول (Length)',
    bodyChest: 'الصدر / البدن (Chest)',
    waist: 'الخصر (Waist)',
    hip: 'الأرداف / الهيب (Hip)',
    shoulder: 'الكتف (Shoulder)',
    sleeve: 'طول الكم (Sleeve)',
    neck: 'الرقبة / الياقة (Neck)',
    flareBottom: 'العرض السفلي / كلوش (Flare)',
    designNotes: 'ملاحظات التصميم والموديل',
    specialInstructions: 'تعليمات الخياطة الخاصة',
    aiEstimate: 'تقدير المقاسات الذكي',
    // Camera / Gallery
    attachPhotos: '٣. صور عينة القماش والتصميم',
    camera: 'كاميرا (Camera)',
    gallery: 'المعرض (Files)',
    clothPhoto: '١. صورة قماش الفستان',
    dressDesignPhoto: '٢. صورة موديل الفستان',
    customerDesignPhoto: '٣. رسم توضيحي من العميل',
    extraPhoto: '٤. صورة نموذج إضافية',
    takePhoto: 'التقاط صورة مباشرة',
    chooseFromGallery: 'اختيار من المعرض',
    deletePhoto: 'حذف الصورة',
    // Actions
    save: 'حفظ',
    saveInvoice: 'حفظ الفاتورة',
    edit: 'تعديل',
    delete: 'حذف',
    view: 'عرض',
    printInvoice: 'طباعة الإيصال',
    saveToGallery: 'حفظ كصورة (PNG)',
    shareInvoice: 'مشاركة الفاتورة',
    sendWhatsApp: 'رسالة واتساب',
    sendWhatsAppPng: 'إرسال الفاتورة PNG عبر واتساب',
    sendReadyWhatsApp: 'إرسال تنبيه جاهزية الملابس عبر واتساب',
    addPayment: '+ تسجيل دفعة جديدة',
    cancel: 'إلغاء',
    search: 'بحث (الاسم، الهاتف، الفاتورة)...',
    close: 'إغلاق',
    confirmDelete: 'هل أنت متأكد من حذف هذا السجل نهائياً؟',
    
    // Karigar / Tailor Ledger
    karigarLedgerTitle: 'سجل أعمال وأجور الخياطين',
    karigarSubTitle: 'متابعة أعمال الخياطين وقطع القص والخياطة وأسعار القطع والدفعات والمتبقي لكل خياط بدقة.',
    addWorkRecord: '+ تسجيل عمل / سلفة لخياط',
    editWorkRecord: 'تعديل قيد الخياط',
    tailorName: 'اسم الخياط *',
    tailorPhone: 'رقم الجوال',
    workType: 'نوع العمل',
    cutting: 'قص (تفصيل)',
    sewing: 'خياطة (تجميع)',
    cuttingAndSewing: 'قص وخياطة معاً',
    otherWork: 'أعمال أخرى',
    cuttingPieces: 'قطع القص',
    sewingPieces: 'قطع الخياطة',
    totalPiecesCount: 'إجمالي القطع',
    ratePerPiece: 'سعر القطعة الواحدة',
    totalWorkValue: 'إجمالي أجر العمل',
    paidAmount: 'المبلغ المدفوع / السلفة',
    balanceDue: 'المتبقي للخياط',
    allEntriesTab: 'سجلات العمل التفصيلية',
    groupedKarigarTab: 'ملخص الخياطين (مجمعة حسب الاسم والهاتف)',
    totalKarigars: 'إجمالي الخياطين',
    totalCuttingPcs: 'إجمالي قطع القص',
    totalSewingPcs: 'إجمالي قطع الخياطة',
    totalKarigarWage: 'إجمالي الأجور المكتسبة',
    totalKarigarPaid: 'إجمالي المدفوعات والسلف',
    totalKarigarDue: 'إجمالي الرصيد المتبقي',
    karigarStatement: 'كشف حساب الخياط',
    noKarigarFound: 'لم يتم العثور على سجلات خياطين.',
    printStatement: 'طباعة كشف حساب الخياط',
    
    // Expenses & Deposits
    expenseDepositTitle: 'سجل المصروفات والإيداعات النقدية',
    expenseDepositSubTitle: 'تسجيل مصاريف المحل اليومية والإيداعات النقدية في الصندوق بدقة عالية.',
    addExpenseDeposit: '+ إضافة مصروف / إيداع نقدي',
    editExpenseDeposit: 'تعديل المعاملة',
    entryType: 'نوع المعاملة',
    expenseType: '💸 مصروفات المحل (Expense)',
    depositType: '💰 إيداع نقدي (Cash Deposit)',
    cashDeposit: 'إيداع نقدي',
    shopExpense: 'مصروفات المحل',
    totalDeposits: 'إجمالي الإيداعات النقدية',
    totalExpenses: 'إجمالي المصروفات',
    netCashBalance: 'الرصيد النقدي في الصندوق (Net Cash)',
    allTransactions: 'جميع المعاملات',
    onlyDeposits: 'الإيداعات فقط',
    onlyExpenses: 'المصروفات فقط',
    category: 'التصنيف',
    amount: 'المبلغ',
    date: 'التاريخ',
    paymentMethodLabel: 'طريقة الدفع / الحساب',
    noTransactionsFound: 'لا توجد سجلات مصروفات أو إيداعات.',
    
    // Catalog
    catalogTitle: 'كتالوج الموديلات والتصاميم',
    dressName: 'اسم الموديل / الفستان',
    catalogCode: 'رمز الكتالوج',
    modelSize: 'المقاس المرجعي',
    addOrderFromCatalog: 'إضافة للطلب',
    shareCatalogCard: 'مشاركة الموديل',
    sendCatalogWhatsAppPng: 'إرسال عبر واتساب مع الصورة',
    addCatalogItem: '+ إضافة تصميم جديد',
    noCatalogFound: 'لا توجد تصاميم في الكتالوج.',
    
    // Reports
    fromDate: 'من تاريخ',
    toDate: 'إلى تاريخ',
    applyFilter: 'تطبيق التصفية',
    avgOrderValue: 'متوسط قيمة الطلب',
    cashPayments: 'المدفوعات النقدية',
    bankPayments: 'المدفوعات البنكية',
    // Settings
    shopSettings: 'إعدادات وبيانات المحل',
    shopName: 'اسم المحل / المشغل',
    shopAddress: 'عنوان المحل',
    crNumber: 'السجل التجاري / الترخيص',
    currency: 'رمز العملة (ر.ع، ر.س، BDT إلخ)',
    multiShop: 'إدارة فروع متعددة',
    language: 'اختيار اللغة (বাংলা / English / हिन्दी / العربية)',
  },
};

export const LANGUAGES = [
  { code: 'BN' as const, label: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩', short: 'বাং' },
  { code: 'EN' as const, label: 'English', nativeName: 'English', flag: '🇬🇧', short: 'ENG' },
  { code: 'HI' as const, label: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', short: 'हिं' },
  { code: 'AR' as const, label: 'Arabic', nativeName: 'العربية', flag: '🇴🇲', short: 'عرب' },
];

